version : '3.0'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    hostname: nginx
    ports:
      - '80:80'

    volumes:
      - ./.config:/home
      - ./nginx_log:/var/log/nginx

    networks:
      - backend
    restart: on-failure
    links:
      - web_service
    depends_on:
      - web_service

  web_service:
    container_name: web_service

    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - ./wonyoung_narajangteo:/srv/project/wonyoung_narajangteo
      - ./.config:/srv/project/.config

    hostname: web_service
    ports:
      - '8000:8000'
    networks:
      - backend
    tty:
      true

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

networks:
  backend:
    driver: 'bridge'